version: '3.9'
services:
  crm-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: crm
      POSTGRES_DB: crm
    ports:
      - '5433:5432'
  ops-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ops
      POSTGRES_PASSWORD: ops
      POSTGRES_DB: ops
    ports:
      - '5434:5432'
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
