import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Diff, Check, X } from 'lucide-react';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { fetchReviewQueue, updateReviewQueueItem, type ReviewQueueItem } from '@/services/api';

export function ReviewQueuePage() {
  const queryClient = useQueryClient();
  const { data: items } = useQuery({ queryKey: ['review-queue'], queryFn: fetchReviewQueue });
  const [feedback, setFeedback] = useState<Record<string, string>>({});

  const mutation = useMutation({
    mutationFn: ({ id, status }: { id: string; status: ReviewQueueItem['status'] }) => updateReviewQueueItem(id, status),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['review-queue'] })
  });

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-2xl font-semibold">Review queue</h1>
        <p className="text-sm text-muted-foreground">Approve or reject AI-generated recommendations before publishing.</p>
      </div>

      <div className="space-y-4">
        {items?.map((item) => (
          <Card key={item.id}>
            <CardHeader className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
              <div>
                <CardTitle className="flex items-center gap-2">
                  <Diff className="h-4 w-4 text-primary" /> {item.title}
                </CardTitle>
                <CardDescription>{item.summary}</CardDescription>
              </div>
              <div className="flex items-center gap-2">
                <Badge variant="outline" className="capitalize">
                  {item.status}
                </Badge>
                <span className="text-xs text-muted-foreground">Generated by {item.generatedBy}</span>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              {item.currentContent && (
                <div>
                  <p className="text-xs font-medium uppercase text-muted-foreground">Current content</p>
                  <pre className="mt-1 max-h-40 overflow-auto rounded-md border border-border bg-muted/40 p-3 text-xs">
                    {item.currentContent}
                  </pre>
                </div>
              )}
              <div>
                <p className="text-xs font-medium uppercase text-muted-foreground">Proposed change</p>
                <pre className="mt-1 max-h-40 overflow-auto rounded-md border border-primary/40 bg-primary/5 p-3 text-xs">
                  {item.proposedChanges}
                </pre>
              </div>
              <div>
                <label className="text-sm font-medium">Feedback</label>
                <Textarea
                  value={feedback[item.id] ?? ''}
                  onChange={(event) => setFeedback((prev) => ({ ...prev, [item.id]: event.target.value }))}
                  placeholder="Optional notes for the automation agent"
                  rows={3}
                />
              </div>
              <div className="flex justify-end gap-2">
                <Button
                  variant="outline"
                  onClick={() => mutation.mutate({ id: item.id, status: 'rejected' })}
                  disabled={mutation.isPending}
                >
                  <X className="mr-2 h-4 w-4" /> Reject
                </Button>
                <Button onClick={() => mutation.mutate({ id: item.id, status: 'approved' })} disabled={mutation.isPending}>
                  <Check className="mr-2 h-4 w-4" /> Approve
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
        {!items?.length && <p className="text-sm text-muted-foreground">No pending recommendations.</p>}
      </div>
    </div>
  );
}
